# Copyright 2026 Avala AI
# SPDX-License-Identifier: Apache-2.0

"""The canonical JSON two implementations are diffed on.

Representation is pinned so that a disagreement is always about the format and never
about how a language spells a number:

* integers are strings, so a 64-bit value survives a JSON parser backed by doubles;
* floats are rounded to a fixed number of decimals before comparison;
* a zero is `0.0` and never `-0.0`, because the sign of a zero says nothing about the
  scene — see `num` and `canonical`;
* a never-fading gaussian's sigma is `null`, never a sentinel a decoder could produce by
  accident;
* `audioSources` is an array, empty when absent, so multiplicity and absence are both
  visible in every implementation's output;
* keys are sorted.

**Nothing here may depend on decoded order.** Gaussians may be reordered freely by an
encoder and readers must not rely on their order, so a summary that did would be asking
two correct decoders to disagree. Per-gaussian rows and the spherical harmonic digest use
the rounded content order defined by `_stable_order`. Aggregates round every addend to
canonical decimal units and sum those units as arbitrary-precision integers, so their
result depends only on the emitted multiset and never on floating-point addition order.

That order rounds before comparing because two implementations may differ in their last
decoded bits. A tie is harmless in the root sample, whose emitted values are the keyed
fields, but composition at time `t` can amplify a tied input difference in `states`.
State rows therefore compare by content key and then by the rounded values they emit;
finite values sort before `null`, and object identity remains an exact integer. State
aggregates instead sum the rounded emitted units exactly, so even surviving ties are
harmless.

**Nor may anything here depend on the machine that decoded it.** The same file summarized
on two platforms must produce the same bytes, or the corpus cannot be regenerated by
whoever is holding it next. Signed zero was the first breach of that: a value at the noise
floor rounds to `-0.0` where the arithmetic lands a hair below zero and `0.0` where it
lands a hair above, and nothing downstream noticed, because `-0.0 == 0.0` is true in every
language the harness compares in.

The summary covers what the file says, not only its gaussians. A record that changes
nothing here is a record an implementation could ignore entirely and still pass, which is
how a feature matrix ends up claiming things the suite never checked.

The same applies field by field, not only record by record. `profile` and `library` are
the Header's first two fields; every SDK could read them and none asserted them, so an
implementation returning an empty string for both was indistinguishable here from one that
decoded them properly. That is the worst shape a gap can take — not a failure, but a
success that proves less than it appears to.
"""

from __future__ import annotations

import json
import math
import struct
import zlib

FLOAT_DECIMALS = 6
#: How many gaussians appear in full. The aggregates cover the rest, so a decoder cannot
#: pass by getting a prefix right.
SAMPLE = 16
#: How many camera keyframes appear in full, so a long trajectory cannot bloat a summary.
CAMERA_KEYFRAMES = 4
#: The same cap for a rig trajectory, which is unbounded for the same reason and worse:
#: a ten-minute capture at 100 Hz is sixty thousand samples.
RIG_SAMPLES = 4
AUDIO_KEYFRAMES = 4


class ExactNumber:
    """A JSON number token that must never pass through a binary float again."""

    __slots__ = ("token",)

    def __init__(self, token: str):
        self.token = token

    def __repr__(self) -> str:
        return f"ExactNumber({self.token!r})"

    def __eq__(self, other) -> bool:
        return isinstance(other, ExactNumber) and self.token == other.token

    def __hash__(self) -> int:
        return hash(self.token)


def num(value) -> float | None:
    """Round for comparison; a non-finite value becomes `null`, and a zero is unsigned.

    The `float()` first is load-bearing: a numpy scalar is not a Python float, so an
    `isinstance` check would let infinity through into JSON, which has no way to spell it.
    """
    if value is None:
        return None
    v = float(value)
    if not math.isfinite(v):
        return None
    # `+ 0.0` reads like a no-op and is not: IEEE 754 says `-0.0 + 0.0` is `+0.0`, and
    # leaves every other value untouched. It is here to erase the sign of a zero, which is
    # a property of the arithmetic path rather than of the scene — a composed value at the
    # noise floor rounds to `-0.0` on one platform and `0.0` on another, and both are the
    # same number. Keeping the sign would put a platform's floating-point behaviour in the
    # corpus where nothing can see it: `-0.0 == 0.0` in Python, so `run.py` compares the
    # two as equal and the difference surfaces only as a spurious diff for whoever
    # regenerates the corpus next.
    return round(v, FLOAT_DECIMALS) + 0.0


def crc(data) -> str:
    """CRC-32 of a byte payload, as a string. Used where a summary needs to prove it read
    the bytes and not merely their length."""
    return str(zlib.crc32(bytes(data)) & 0xFFFFFFFF)


def canonical(scene_summary: dict) -> str:
    """Serialize a summary, unsigning every zero on the way out.

    `num` is the front door and most values arrive through it, but not every summary is
    built by `summarize`: the keyframe-delta corpus comes from
    `fourdgs.keyframe_delta_file.states_json`, which rounds with its own helper, and the
    next model to arrive will very likely bring a third. Normalizing here makes the
    unsigned zero a property of the canonical form itself rather than of whichever helper
    happened to produce a number, so a path added later gets the guarantee instead of
    reintroducing #153 somewhere new.
    """
    normalized = _unsigned_zeros(scene_summary)
    strings: set[str] = set()

    def collect_strings(value):
        if isinstance(value, dict):
            for key, item in value.items():
                strings.add(str(key))
                collect_strings(item)
        elif isinstance(value, (list, tuple)):
            for item in value:
                collect_strings(item)
        elif isinstance(value, str):
            strings.add(value)

    collect_strings(normalized)
    marker_prefix = "\0fourdgs-exact-number\0"
    while any(marker_prefix in value for value in strings):
        marker_prefix += "#"

    replacements: dict[str, str] = {}

    def mark_exact(value):
        if isinstance(value, ExactNumber):
            marker = f"{marker_prefix}{len(replacements)}"
            replacements[json.dumps(marker)] = value.token
            return marker
        if isinstance(value, dict):
            return {key: mark_exact(item) for key, item in value.items()}
        if isinstance(value, (list, tuple)):
            return [mark_exact(item) for item in value]
        return value

    text = json.dumps(mark_exact(normalized), sort_keys=True, indent=2, allow_nan=False)
    for marker, token in replacements.items():
        text = text.replace(marker, token)
    return text


def _exact_sum(values) -> ExactNumber | None:
    """Sum canonical 10^-6 units exactly, or return null for a non-finite addend.

    Conversion goes through fixed-point decimal text rather than multiplying a binary
    float by the scale. Both each scaled addend and the accumulator are Python integers,
    whose precision is bounded by memory rather than a machine word.
    """
    scale = 10**FLOAT_DECIMALS
    total = 0
    for value in values:
        rounded = num(value)
        if rounded is None:
            return None
        fixed = f"{rounded:.{FLOAT_DECIMALS}f}"
        negative = fixed.startswith("-")
        if negative:
            fixed = fixed[1:]
        whole, fraction = fixed.split(".")
        units = int(whole) * scale + int(fraction)
        total += -units if negative else units

    negative = total < 0
    whole, fraction = divmod(abs(total), scale)
    decimal = f"{fraction:0{FLOAT_DECIMALS}d}".rstrip("0") or "0"
    return ExactNumber(f"{'-' if negative else ''}{whole}.{decimal}")


def _unsigned_zeros(value):
    """A summary with `-0.0` replaced by `0.0` and every other value left alone.

    Walks the structure rather than the serialized text: `-0.0` is spelled several ways in
    JSON output depending on magnitude, and a string substitution would also reach inside
    the string-encoded integers this format uses.
    """
    if isinstance(value, dict):
        return {k: _unsigned_zeros(v) for k, v in value.items()}
    if isinstance(value, (list, tuple)):
        return [_unsigned_zeros(v) for v in value]
    # `bool` is a subclass of `int` and not of `float`, so it falls through untouched, and
    # so do the string-encoded integers. See `num` for why `+ 0.0` is not a no-op.
    if isinstance(value, float):
        return value + 0.0
    return value


def summarize(
    header,
    gaussians,
    audio_sources,
    chunk_intervals,
    *,
    camera=None,
    metadata=(),
    attachments=(),
    statistics=None,
    summary_offsets=(),
    summary_crc_ok=None,
    provenance=None,
    objects=None,
) -> dict:
    """The statement every implementation must agree on for a variant."""
    n = gaussians.count
    content_keys = _stable_keys(gaussians)
    order = sorted(range(n), key=content_keys.__getitem__)
    sample = order[:SAMPLE]

    def rows(arr, width):
        return [[num(v) for v in arr[i][:width]] for i in sample]

    never_fades = 0
    still = 0
    for i in order:
        if not math.isfinite(float(gaussians.sigma_t[i])):
            never_fades += 1
        if (
            abs(float(gaussians.motions[i][0]))
            + abs(float(gaussians.motions[i][1]))
            + abs(float(gaussians.motions[i][2]))
            == 0.0
        ):
            still += 1

    return {
        "gaussianCount": str(n),
        "durationSec": num(header.duration_sec),
        "cutoff": num(header.cutoff),
        # The Header's first two fields. Readable in every SDK from the start and asserted
        # by none of them, which is a hiding place rather than an omission: a binding that
        # returned an empty string for both — because it never wired them through — read
        # successfully, produced a summary identical to a correct one, and passed. The C++
        # binding did exactly that once. A field that no expectation mentions is a field an
        # implementation can decline to decode.
        "profile": header.profile,
        "library": header.library,
        "shDegree": int(header.sh_degree),
        "temporalModel": header.temporal_model,
        "hasAudio": bool(header.has_audio),
        "audioSources": [
            _audio_source(source, header.duration_sec / 2)
            for source in sorted(audio_sources, key=lambda s: s.source_id)
        ],
        "chunkIntervals": [[num(a), num(b)] for a, b in chunk_intervals],
        "headerAttributes": {k: v for k, v in sorted(dict(header.attributes).items())},
        "metadataRecords": [
            {"name": m.name, "entries": {k: v for k, v in sorted(dict(m.entries).items())}} for m in metadata
        ],
        "attachments": [
            {
                "name": a.name,
                "mediaType": a.media_type,
                "byteLength": str(len(a.data)),
                "crc": crc(a.data),
            }
            for a in attachments
        ],
        "camera": None if camera is None else _camera(camera),
        "statistics": None
        if statistics is None
        else {
            "gaussianCount": str(statistics.gaussian_count),
            "chunkCount": str(statistics.chunk_count),
            "durationSec": num(statistics.duration_sec),
            "aabb": [num(v) for v in statistics.aabb],
        },
        "summaryOffsets": [
            {
                "groupOpcode": str(s.group_opcode),
                "groupStart": str(s.group_start),
                "groupLength": str(s.group_length),
            }
            for s in summary_offsets
        ],
        "summaryCrcOk": summary_crc_ok,
        # Omitted entirely when the file carries no provenance, which is deliberate and
        # is NOT the `audioSources` convention above.
        #
        # `audioSources` is empty when absent because audio presence is a property of
        # every file — the Header declares it either way — so both paths have to be
        # visible in every variant or one of them is never checked. Provenance has no such
        # flag and no such duty: a file that carries none is a file the record family does
        # not apply to. Emitting `"provenance": null` on all thirty-four pre-existing variants
        # would have changed every committed expectation and broken three SDKs that
        # correctly skip the records by length — which is to say it would have reported
        # the forward-compatibility mechanism working as a conformance failure. Absence
        # here is the section not applying; the thirty-four variants without it are the
        # assertion that a file without provenance is unchanged by the family existing.
        **({} if not provenance else {"provenance": _provenance(provenance)}),
        **(
            {}
            if not objects and getattr(gaussians, "object_id", None) is None
            else _objects_and_states(header, gaussians, objects, order, content_keys)
        ),
        "sh": _spherical_harmonics(gaussians, order),
        "sample": {
            "positions": rows(gaussians.positions, 3),
            "scales": rows(gaussians.scales, 3),
            "rotations": rows(gaussians.rotations, 4),
            "colors": rows(gaussians.colors, 4),
            "motions": rows(gaussians.motions, 3),
            "muT": [num(gaussians.mu_t[i]) for i in sample],
            "sigmaT": [num(gaussians.sigma_t[i]) for i in sample],
            "winLo": [num(gaussians.win_lo[i]) for i in sample],
            "winHi": [num(gaussians.win_hi[i]) for i in sample],
            **(
                {}
                if getattr(gaussians, "object_id", None) is None
                else {"objectIds": [str(int(gaussians.object_id[i])) for i in sample]}
            ),
        },
        "aggregate": {
            # Exact canonical-unit sums make the aggregate a function of the emitted
            # multiset, not resident order or non-associative binary addition.
            "positionSum": [_exact_sum(gaussians.positions[:, axis]) for axis in range(3)],
            "opacitySum": _exact_sum(gaussians.colors[:, 3]),
            "neverFadesCount": str(never_fades),
            "zeroMotionCount": str(still),
        },
    }


def _objects_and_states(header, gaussians, objects, order, content_keys) -> dict:
    """Object records plus post-track gaussian states at three scene-clock probes.

    Stored fields alone do not prove reconstruction. The states make the normative
    base-then-track order visible, including orientation, while the canonical gaussian
    order keeps the result independent of chunk and decoder order.
    """
    from fourdgs.object_layer import ObjectLayer
    from fourdgs.provenance import pose_at

    layer = objects if objects is not None else ObjectLayer()
    table = layer.table
    tracks = []
    for track in layer.tracks:
        probes = _probe_times(track)
        tracks.append(
            {
                "objectId": str(track.object_id),
                "interpolation": int(track.interpolation),
                "sampleCount": str(track.sample_count),
                "posesAt": [_pose_row(probe, pose_at(track, probe)) for probe in probes],
            }
        )

    duration = max(0.0, float(header.duration_sec))
    probe_times = [0.0, 0.5 * duration, max(0.0, duration - 1e-6)]
    states = []
    for t in probe_times:
        base = gaussians.state_at(t, header.cutoff)
        centers, orientations = layer.apply(
            centers=base["centers"],
            orientations=base["orientations"],
            object_ids=base["object_id"],
            t=t,
        )
        row_for_index = {int(index): row for row, index in enumerate(base["indices"])}
        live_indices = [index for index in order if index in row_for_index]
        # The content key deliberately rounds before comparison, so distinct rows can
        # tie.  A state row is composed after that key is formed and can amplify a tied
        # input difference.  Break only those ties by the rounded row this block emits.
        live_indices.sort(
            key=lambda index: (
                content_keys[index],
                _state_row_key(
                    centers[row_for_index[index]],
                    orientations[row_for_index[index]],
                    base["object_id"][row_for_index[index]],
                ),
            )
        )
        live_rows = [row_for_index[index] for index in live_indices]
        sample_rows = live_rows[:SAMPLE]
        states.append(
            {
                "t": num(t),
                "liveCount": str(len(base["indices"])),
                "sample": {
                    "positions": [[num(value) for value in centers[row]] for row in sample_rows],
                    "orientations": [[num(value) for value in orientations[row]] for row in sample_rows],
                    "objectIds": [str(int(base["object_id"][row])) for row in sample_rows],
                },
                "aggregate": {
                    # Round each addend before exact integer-unit addition. Sorting raw
                    # floats first would still leave surviving rounded ties order-sensitive.
                    "positionSum": [_exact_sum(centers[row][axis] for row in live_rows) for axis in range(3)],
                    "opacitySum": _exact_sum(base["opacity"][row] for row in live_rows),
                },
            }
        )

    entries = []
    if table is not None:
        for entry in table.entries:
            embedding = entry.embedding
            embedding_bytes = b"" if embedding is None else struct.pack(f"<{len(embedding)}f", *embedding)
            entries.append(
                {
                    "objectId": str(entry.object_id),
                    "label": entry.label,
                    "anchor": [num(value) for value in entry.anchor],
                    # The decoded dynamics values, not merely their presence: a summary that
                    # said only whether the record was there would pass a decoder that read
                    # the nine floats and exposed zeros. `None` when the entry carries none.
                    "dynamics": None
                    if entry.dynamics is None
                    else {
                        "velocity": [num(v) for v in entry.dynamics[0]],
                        "angularVelocity": [num(v) for v in entry.dynamics[1]],
                        "acceleration": [num(v) for v in entry.dynamics[2]],
                    },
                    "hasEmbedding": embedding is not None,
                    "embeddingCrc": None if embedding is None else crc(embedding_bytes),
                }
            )

    return {
        "objects": {
            "embeddingDim": 0 if table is None else int(table.embedding_dim),
            "table": entries,
            "tracks": tracks,
        },
        "states": states,
    }


def _provenance(prov) -> dict:
    """Every readable provenance field, plus the arithmetic the fields imply.

    The fields alone would not be enough. `Header.profile` was readable in every SDK
    and asserted by none, so a binding that returned an empty string passed — and the
    same hiding place exists one level up here: two implementations can agree on every
    stored quaternion and still disagree about the pose halfway between two of them,
    because slerp has a sign convention and clamping has an edge. So the summary
    carries the interpolated poses as well as the samples, at probe times derived from
    the decoded data alone, including one before the first sample and one after the
    last.
    """
    from fourdgs.provenance import pose_at

    trajectories = []
    for t in prov.trajectories:
        probes = _probe_times(t)
        trajectories.append(
            {
                "name": t.name,
                "interpolation": int(t.interpolation),
                "sampleCount": str(t.sample_count),
                "samples": [
                    {
                        "time": num(t.times[i]),
                        "rotation": [num(v) for v in t.rotations[i]],
                        "translation": [num(v) for v in t.translations[i]],
                    }
                    for i in range(min(t.sample_count, RIG_SAMPLES))
                ],
                "posesAt": [_pose_row(probe, pose_at(t, probe)) for probe in probes],
            }
        )

    return {
        "frames": [
            {
                "name": f.name,
                "handedness": int(f.handedness),
                "upAxis": int(f.up_axis),
                "forwardAxis": int(f.forward_axis),
                "lengthUnit": int(f.length_unit),
                "metresPerUnit": num(f.metres_per_unit),
                # The resolution rule, per frame: a consumer handed a file whose two unit
                # fields disagree still has to produce one number, and this is it.
                "metresPerUnitResolved": num(prov.metres_per_unit(f.name)),
            }
            for f in prov.frames
        ],
        "anchors": [
            {
                "frameName": a.frame_name,
                "latitudeDeg": num(a.latitude_deg),
                "longitudeDeg": num(a.longitude_deg),
                "altitudeM": num(a.altitude_m),
                "headingDeg": num(a.heading_deg),
            }
            for a in prov.anchors
        ],
        "sensors": [
            {
                "name": s.name,
                "modality": s.modality,
                "cameraModel": int(s.camera_model),
                "widthPx": str(s.width_px),
                "heightPx": str(s.height_px),
                "fx": num(s.fx),
                "fy": num(s.fy),
                "cx": num(s.cx),
                "cy": num(s.cy),
                "distortion": [num(v) for v in s.distortion],
                "rotation": [num(v) for v in s.rotation],
                "translation": [num(v) for v in s.translation],
                "poseReference": int(s.pose_reference),
                "rigName": s.rig_name,
            }
            for s in prov.sensors
        ],
        "trajectories": trajectories,
        # The composition rule, which is the one thing here no single record states and
        # every consumer of a moving rig depends on.
        "sensorPosesAt": [
            _pose_row(probe, prov.sensor_pose_at(s.name, probe), sensor=s.name)
            for s in prov.sensors
            for probe in (_sensor_probe_time(prov, s),)
        ],
    }


def _probe_times(trajectory) -> list[float]:
    """Times a summary evaluates a trajectory at, derived from the trajectory itself.

    Two of the five are outside the sample range on purpose: clamping is a rule, and a
    rule no expectation exercises is a rule an implementation can decline to have.
    """
    if trajectory.sample_count == 0:
        return []
    first, last = trajectory.times[0], trajectory.times[-1]
    return [first - 0.5, first, first / 2 + last / 2, last, last + 0.5]


def _sensor_probe_time(prov, sensor) -> float:
    """When to evaluate a sensor's scene pose: the midpoint of the rig it rides."""
    # The empty string is a legal trajectory name — the default capture rig — and
    # `sensor_pose_at` resolves it, so skipping the lookup summarized a moving unnamed
    # rig at t=0 and never exercised its composed pose. Fall back to 0 only when the
    # trajectory is genuinely absent or carries no samples.
    trajectory = prov.trajectory(sensor.rig_name)
    if trajectory is None or trajectory.sample_count == 0:
        return 0.0
    return trajectory.times[0] / 2 + trajectory.times[-1] / 2


def _pose_row(t: float, pose, sensor: str | None = None) -> dict:
    row = {"time": num(t)}
    if sensor is not None:
        row["sensor"] = sensor
    if pose is None:
        row["rotation"] = None
        row["translation"] = None
        return row
    row["rotation"] = [num(v) for v in pose.rotation]
    row["translation"] = [num(v) for v in pose.translation]
    return row


def _camera(camera) -> dict:
    return {
        "fovYDeg": num(camera.fov_y_deg),
        "position": [num(v) for v in camera.position],
        "target": [num(v) for v in camera.target],
        "keyframeCount": str(len(camera.times)),
        "keyframes": [
            {
                "time": num(camera.times[i]),
                "position": [num(v) for v in camera.positions[i]],
                "target": [num(v) for v in camera.targets[i]],
            }
            for i in range(min(len(camera.times), CAMERA_KEYFRAMES))
        ],
        "interpolation": camera.interpolation,
        "loop": bool(camera.loop),
    }


def _audio_source(source, sample_time: float) -> dict:
    state = source.state_at(sample_time)
    return {
        "sourceId": str(source.source_id),
        "name": source.name,
        "codec": source.codec,
        "channelLayout": source.channel_layout,
        "startSec": num(source.start_sec),
        "durationSec": num(source.duration_sec),
        "gain": num(source.gain),
        "spatial": bool(source.spatial),
        "loop": bool(source.loop),
        "position": [num(v) for v in source.position],
        "rotation": [num(v) for v in source.rotation],
        "keyframeCount": str(len(source.keyframes)),
        "keyframes": [
            {
                "time": num(keyframe.time),
                "position": [num(v) for v in keyframe.position],
                "rotation": [num(v) for v in keyframe.rotation],
            }
            for keyframe in source.keyframes[:AUDIO_KEYFRAMES]
        ],
        "interpolation": source.interpolation,
        "stateAtHalf": {
            "active": bool(state.active),
            "localTime": num(state.local_time),
            "position": [num(v) for v in state.position],
            "rotation": [num(v) for v in state.rotation],
            "gain": num(state.gain),
        },
        "byteLength": str(len(source.data)),
        "crc": crc(source.data),
    }


def _spherical_harmonics(gaussians, order) -> dict | None:
    """Degree, width and a checksum of the coefficients in content order.

    A digest rather than the coefficients themselves: degree 2 over 512 gaussians is
    12,288 bytes, which would swamp the expectation without proving anything the checksum
    does not. Taken in content order so that two decoders which visit gaussians
    differently still agree.
    """
    sh = getattr(gaussians, "sh", None)
    if sh is None or gaussians.sh_degree == 0:
        return None
    coefficients = sh.shape[1] // 3
    payload = bytearray()
    for i in order:
        payload += bytes(bytearray(int(v) for v in sh[i]))
    return {
        "degree": int(gaussians.sh_degree),
        "coefficients": str(coefficients),
        "crc": crc(payload),
    }


def _stable_keys(gaussians) -> list[tuple]:
    """Build the portable content key for each gaussian.

    Chunking and Morton ordering are encoder choices, so decoded order is not part of the
    contract — but a comparison needs *some* order. The key is the gaussian's whole
    decoded state, rounded exactly as the summary rounds it, with its spherical harmonic
    coefficients and object membership last. Exact decoded values are deliberately not a
    tiebreaker: independently implemented decoders may differ in their last bits.
    """
    sh = getattr(gaussians, "sh", None)
    keys: list[tuple] = []
    for i in range(gaussians.count):
        row = []
        for arr, width in (
            (gaussians.positions, 3),
            (gaussians.scales, 3),
            (gaussians.rotations, 4),
            (gaussians.colors, 4),
            (gaussians.motions, 3),
        ):
            row += [_sortable(arr[i][k]) for k in range(width)]
        for value in (
            gaussians.mu_t[i],
            gaussians.sigma_t[i],
            gaussians.win_lo[i],
            gaussians.win_hi[i],
        ):
            row.append(_sortable(value))
        if sh is not None:
            row += [int(v) for v in sh[i]]
        object_id = getattr(gaussians, "object_id", None)
        if object_id is not None:
            row.append(int(object_id[i]))
        keys.append(tuple(row))
    return keys


def _stable_order(gaussians) -> list[int]:
    """Sort gaussians by their portable rounded content keys."""
    keys = _stable_keys(gaussians)
    return sorted(range(gaussians.count), key=keys.__getitem__)


def _sortable(value) -> float:
    """A comparison key: rounded like the summary, with infinity kept as infinity so the
    two languages order never-fading gaussians identically."""
    v = float(value)
    if math.isnan(v):
        return math.inf
    if math.isinf(v):
        return v
    return round(v, FLOAT_DECIMALS)


def _state_scalar_key(value) -> tuple[int, float]:
    rounded = num(value)
    return (1, 0.0) if rounded is None else (0, rounded)


def _state_row_key(center, orientation, object_id) -> tuple:
    """Portable order over exactly the rounded values a state sample emits."""
    return (*(_state_scalar_key(v) for v in (*center, *orientation)), int(object_id))
