// @ts-check
/* eslint-env node */

// Every entry is listed explicitly rather than autogenerated, so that ordering and
// sidebar labels live here instead of in the documents. The specification pages in
// particular are the normative text and are left exactly as written.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  guidesSidebar: [
    { type: "doc", id: "guides/index", label: "Overview" },
    { type: "doc", id: "guides/concepts", label: "Concepts" },
    { type: "doc", id: "guides/interop-gltf", label: "glTF interoperability" },
    {
      type: "category",
      label: "Getting started",
      collapsed: false,
      items: [
        { type: "doc", id: "guides/getting-started/encode-python", label: "Encode in Python" },
        { type: "doc", id: "guides/getting-started/decode-python", label: "Decode in Python" },
        { type: "doc", id: "guides/getting-started/decode-web", label: "Decode in a browser" },
        { type: "doc", id: "guides/getting-started/decode-rust", label: "Decode in Rust" },
        { type: "doc", id: "guides/getting-started/decode-cpp", label: "Decode in C++" },
        { type: "doc", id: "guides/getting-started/decode-swift", label: "Decode in Swift" },
      ],
    },
  ],

  specSidebar: [
    { type: "doc", id: "spec/index", label: "Specification" },
    { type: "doc", id: "spec/registry", label: "Registry" },
    { type: "doc", id: "spec/notes", label: "Implementation notes" },
  ],

  referenceSidebar: [
    { type: "doc", id: "reference/index", label: "Feature support matrix" },
    { type: "doc", id: "reference/conformance", label: "Conformance suite" },
  ],
};

module.exports = sidebars;
